server:
  port: 18086
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:7001/eureka
  instance:
    prefer-ip-address: true
feign:
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 30000 #缺省为1000 https://blog.csdn.net/qq_18685059/article/details/84909533
spring:
  application:
    name: rabbitmq
  main:
    allow-bean-definition-overriding: true
  rabbitmq:
    host: 192.168.211.132
    username: guest
    password: guest
    port: 5672